General refactoring

diff --git a/bin/project_add b/bin/project_add
--- a/bin/project_add
+++ b/bin/project_add
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
 ########################################################################
-# 2014-09-07 Lukas Bestle mail@lukasbestle.com
+# Copyright 2014 Lukas Bestle <project-projectr@lukasbestle.com>
+# License   MIT
 ########################################################################
 # Creates a project directory, bootstraps it with a basic directory
 # structure and optionally prepares it for deployments.
 #
 # Usage: project_add <project> [<origin>]
 #        
-#        <project>	Path to the project
-#        <origin>		Repository URL and branch name (<url>[#<branch>])
+#        <project>  Path to the project
+#        <origin>   Repository URL and branch name (<url>[#<branch>])
 ########################################################################
 
 project="$1"
@@ -29,7 +30,7 @@ fi
 # Create project directory
 echo -e "\033[1mCreating project at \033[34m$project\033[0;1m...\033[0m"
 if ! (mkdir "$project" && mkdir "$project/data" && touch "$project/.project"); then
-	echo -e "\033[31mCould not create directory structure at \033[34m$project\033[31m.\033[0m" >&2
+	echo -e " => \033[31mCould not create directory structure at \033[34m$project\033[31m.\033[0m" >&2
 	exit 1
 fi
 echo -e " => \033[32mSuccess.\033[0m"
@@ -49,10 +50,8 @@ if [[ -n "$origin" ]]; then
 else
 	echo -e "\033[1mInitializing local project directory at \033[34m$project/current\033[0;1m...\033[0m"
 	if ! mkdir "$project/current"; then
-		echo -e "\033[31mCould not create local project directory.\033[0m" >&2
+		echo -e " => \033[31mCould not create local project directory.\033[0m" >&2
 		exit 1
 	fi
 	echo -e " => \033[32mSuccess.\033[0m"
-	
-	exit 0
 fi
diff --git a/bin/site_link b/bin/site_link
--- a/bin/site_link
+++ b/bin/site_link
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 ########################################################################
-# 2014-09-07 Lukas Bestle mail@lukasbestle.com
+# Copyright 2014 Lukas Bestle <project-projectr@lukasbestle.com>
+# License   MIT
 ########################################################################
 # Creates a link for the webserver pointing a domain to a site.
 #
 # Usage: site_link <site> <domain>
 #        
-#        <site>		Name of the site (directory in ~/web/sites/)
-#        <domain>	FQDN of the domain (like "example.com")
+#        <site>    Name of the site (directory in ~/web/sites/)
+#        <domain>  FQDN of the domain (like "example.com")
 ########################################################################
 
 site="$1"
@@ -40,7 +41,7 @@ fi
 # Create link
 echo -e "\033[1mCreating link from site \033[34m$site\033[0;1m to domain \033[34m$domain\033[0;1m...\033[0m"
 if ! ln -s "sites/$site/current" "$HOME/web/$domain"; then
-	echo -e "\033[31mCould not create link at \033[34m$HOME/web/$domain\033[31m.\033[0m" >&2
+	echo -e " => \033[31mCould not create link at \033[34m$HOME/web/$domain\033[31m.\033[0m" >&2
 	exit 1
 fi
 echo -e " => \033[32mSuccess.\033[0m"
@@ -50,7 +51,6 @@ echo -e "\033[1mAdding domain to site's domains (\033[34m.domains\033[0;1m file)
 echo "$domain" >> "$HOME/web/sites/$site/.domains"
 if [[ $? == 0 ]]; then
 	echo -e " => \033[32mSuccess.\033[0m"
-	exit 0
 else
 	echo -e " => \033[31mSomething went wrong.\033[0m" >&2
 	exit 1
diff --git a/bin/site_unlink b/bin/site_unlink
--- a/bin/site_unlink
+++ b/bin/site_unlink
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
 ########################################################################
-# 2014-09-07 Lukas Bestle mail@lukasbestle.com
+# Copyright 2014 Lukas Bestle <project-projectr@lukasbestle.com>
+# License   MIT
 ########################################################################
 # Removes a link for the webserver pointing a domain to a site.
 #
 # Usage: site_unlink <site> [<domain>]
 #        
-#        <site>		Name of the site (directory in ~/web/sites/)
-#        <domain>	FQDN of the domain (like "example.com")
-#                	If not given, the site is completely unlinked
+#        <site>    Name of the site (directory in ~/web/sites/)
+#        <domain>  FQDN of the domain (like "example.com")
+#                  If not given, the site is completely unlinked.
 ########################################################################
 
 site="$1"
@@ -65,17 +66,16 @@ fi
 # Remove link
 echo -e "\033[1mRemoving link from site \033[34m$site\033[0;1m to domain \033[34m$domain\033[0;1m...\033[0m"
 if ! rm -f "$HOME/web/$domain"; then
-	echo -e "\033[31mCould not remove link at \033[34m$HOME/web/$domain\033[31m.\033[0m" >&2
+	echo -e " => \033[31mCould not remove link at \033[34m$HOME/web/$domain\033[31m.\033[0m" >&2
 	exit 1
 fi
 echo -e " => \033[32mSuccess.\033[0m"
 
 # Remove from site's domains
 echo -e "\033[1mRemoving domain from site's domains (\033[34m.domains\033[0;1m file)...\033[0m"
-sed -i "/$domain/d" "$HOME/web/sites/$site/.domains"
+sed -i "/${domain//\//\/}/d" "$HOME/web/sites/$site/.domains" # Replace / with \/ because of the sed separators
 if [[ $? == 0 ]]; then
 	echo -e " => \033[32mSuccess.\033[0m"
-	exit 0
 else
 	echo -e " => \033[31mSomething went wrong.\033[0m" >&2
 	exit 1
